# -*- coding: utf-8 -*-
"""Analyze_Netflix-Shows.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tblvYEh1funPCM49NMwdFCfULwCME409
"""

!pip install plotly

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns;
import random
import plotly.express as px

"""**INFORMATION ABOUT NETFLIX DATASET**"""

netflix = pd.read_csv("netflix_titles.csv")

netflix.info()

netflix.head()

"""**A. Visualize shows vs movies**"""

sns.set(style='darkgrid')
ax = sns.countplot(x='type', data=netflix, palette='Set3')

"""**B. Visualize Distribution of shows by country**"""

#Divide Countries
for_country = netflix.copy()
for_country['split_country'] = for_country['country'].str.split(', ')
expanded_netflix_country = for_country.explode('split_country')

# Group Countries
grouped_netflix_country= expanded_netflix_country.groupby('split_country').agg({'type': 'count'}).reset_index()
grouped_netflix_country.columns = ['country', 'count']

# Sort Countries
grouped_netflix_country = grouped_netflix_country.sort_values(by='count', ascending=False)

grouped_netflix_country.head(150)

plt.figure(figsize=(20,25))

plt.title("Content creating countries")

sns.barplot(y=list(grouped_netflix_country['country']), x=list(grouped_netflix_country['count']))

plt.ylabel("Countries")

#The total of the top 10 countries that distribute the most shows and the other countries other than the top 10 countries

top_countries = grouped_netflix_country.head(10)

other_count = grouped_netflix_country['count'][10:].sum()

new_countries = pd.concat([top_countries, pd.DataFrame({'country': ['Others'], 'count': [other_count]})])

plt.figure(figsize=(10, 5))
sns.barplot(x='count', y='country', data=new_countries, palette='rainbow')
plt.xlabel("Number of Shows")
plt.ylabel("Country")
plt.title("Number of Shows Distributed by Top 10 Countries and Others")
plt.show()

#Comparison of United States and All other countries

other_count = grouped_netflix_country[grouped_netflix_country['country'] != 'United States']['count'].sum()

comparison_data = pd.DataFrame({'country': ['United States', 'Others'],
                               'count': [grouped_netflix_country[grouped_netflix_country['country'] == 'United States']['count'].values[0], other_count]})

plt.figure(figsize=(15, 5))
sns.barplot(x='count', y='country', data=comparison_data, palette='rainbow')

for i, count in enumerate(comparison_data['count']):
    plt.text(count + 50 , i, str(count), va='center')

plt.xlabel("Number of Shows")
plt.ylabel("Country")
plt.title("Number of Shows Distributed by United States and Others")
plt.show()

"""**C. Visualize 10 shows and in each year and genre**

*10 Shows for each genre*
"""

#Divide Genres
for_genres = netflix.copy()
for_genres['listed_in_split'] = for_genres['listed_in'].str.split(', ')
expanded_netflix = for_genres.explode('listed_in_split')

# Group Genres
grouped_netflix_genre = expanded_netflix.groupby('listed_in_split').agg({'type': 'count'}).reset_index()
grouped_netflix_genre.columns = ['listed_in', 'count']

# Sort Genres
grouped_netflix_genre = grouped_netflix_genre.sort_values(by='count', ascending=False)

expanded_netflix.head()

selected_shows_genre = []

for genre in grouped_netflix_genre['listed_in']:
    shows = expanded_netflix[expanded_netflix['listed_in_split'] == genre]
    random_shows = shows.sample(n=10, random_state=42)
    selected_shows_genre.append(random_shows[['listed_in_split', 'title','type','director','country','release_year','description']])

df_selected_shows_genre = pd.concat(selected_shows_genre)

columns_to_visualize = ['listed_in_split', 'title']
additional_columns = ['type', 'director', 'country', 'description']

df_visualize_year = df_selected_shows_genre[columns_to_visualize + additional_columns]

fig = px.treemap(df_visualize_year, path=columns_to_visualize, color='listed_in_split',
                 hover_data=additional_columns, color_continuous_scale='Blues')
fig.show()

"""*10 Shows for each year*"""

# Group Years
grouped_year_netflix = netflix.groupby('release_year').agg({'type': 'count'}).reset_index()
grouped_year_netflix.columns = ['release_year', 'count']

# Sort Genres
grouped_year_netflix = grouped_year_netflix.sort_values(by='release_year', ascending=False)

print(grouped_year_netflix)

selected_shows_for_year = []

for year in grouped_year_netflix['release_year']:
    shows = netflix[netflix['release_year'] == year]

    if len(shows) > 10:
        random_shows = shows.sample(n=10, random_state=42)
    else:
        random_shows = shows

    selected_shows_for_year.append(random_shows[['title','type','director','country','release_year','description']])

df_selected_shows_year = pd.concat(selected_shows_for_year)

columns_to_visualize = ['release_year', 'title']
additional_columns = ['type', 'director', 'country', 'description']

df_visualize_year = df_selected_shows_year[columns_to_visualize + additional_columns]

fig = px.treemap(df_visualize_year, path=columns_to_visualize, color='release_year',
                 hover_data=additional_columns, color_continuous_scale='Blues')
fig.show()

"""**D. Clean Data**"""

netflix.isnull().sum()

netflix.fillna({'director':'Unavailable'},inplace=True)
netflix.fillna({'country':'Unavailable'},inplace=True)
netflix.fillna({'cast':'Unavailable'},inplace=True)
netflix.fillna({'rating':'Unavailable'},inplace=True)
netflix.fillna({'date_added':'Unavailable'},inplace=True)
netflix.fillna({'duration':'Unavailable'},inplace=True)

netflix.isnull().sum()

netflix.head(5)

"""**E. Discussion Of Findings**

The first chart shows the number of movies and TV shows streamed on Netflix. As can be clearly seen, the movies released are more than 2 times the number of TV shows.

The second chart shows the distribution of shows broadcast by countries. The United States tops this chart, with a much higher number than other countries. In addition, the United States seems to have a show number that exceeds the total number of shows released by other countries other than the top 10 countries.

If we comparing United States with all other countries, We can clearly see that, United States alone aired more than half of the shows broadcast by all other countries.

When we look at the distribution of shows by genres, we see that there are 42 different genres.

When we examine the distribution of shows by years, we see shows shot since 1925 and broadcast on Netflix. Of course, the amount of shows shot before 1980 and released on Netflix in this table is considerably less than in more recent years, considering the technological possibilities of that period.

For data cleaning, instead of removing the null values ​​from the dataset, I chose to replace those values ​​with 'Unavailable' because I didn't want to lose data from the dataset.
"""