# -*- coding: utf-8 -*-
"""MockData_Create_Export.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PT9rT98mqxO9vQ50KmBQLKeDYsv1LJy3
"""

!pip install faker

import pandas as pd
from faker import Faker
import numpy as np
import random
import time
import math

# Load the Netflix-Shows file
netflix_shows = pd.read_csv("netflix_titles.csv")

#Divide Countries
for_country = pd.read_csv("netflix_titles.csv")
for_country['split_country'] = for_country['country'].str.split(', ')
expanded_netflix_country = for_country.explode('split_country')

# Group Countries
grouped_netflix_country= expanded_netflix_country.groupby('split_country').agg({'type': 'count'}).reset_index()
grouped_netflix_country.columns = ['country', 'count']

# Sort Countries
grouped_netflix_country = grouped_netflix_country.sort_values(by='count', ascending=False)

# Generate mock viewer data
fake = Faker()

num_users = 5000
mock_data = []

user_watched_movies = {}

for _ in range(num_users):
    username = fake.user_name()
    country = random.choice(grouped_netflix_country['country'])
    num_watched = random.randint(1, 5)

    watched_movies = set()

    for _ in range(num_watched):
        title = random.choice(netflix_shows['title'])

        # If the user has not watched this movie before, add the movie to the mock dataset and add it to the watched movies set
        if title not in watched_movies:
            watched_movies.add(title)

            date_watched = fake.date_between(start_date='-1y', end_date='today')
            percentage_watched = random.randint(10, 100)

            mock_data.append([username, country, title, date_watched, percentage_watched])

    user_watched_movies[username] = watched_movies

# Create a DataFrame from the mock data
columns = ['Username', 'Country of User', 'Title', 'Date Watched', 'Percentage Watched']
mock_df = pd.DataFrame(mock_data, columns=columns)

mock_df.info()

mock_df.head(20)

mock_df.to_csv('mock_data.csv', index=False)